name: Deploy GH Pages
on:
  push:
    branches:
      - main
    paths: ["src/**"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          npm ci
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs-build # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch